# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handhelper_add_note_window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addNoteWidget(object):
    def setupUi(self, addNoteWidget):
        addNoteWidget.setObjectName("addNoteWidget")
        addNoteWidget.resize(621, 347)
        self.horizontalLayout = QtWidgets.QHBoxLayout(addNoteWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(addNoteWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.chooseEventBox = QtWidgets.QComboBox(addNoteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseEventBox.sizePolicy().hasHeightForWidth())
        self.chooseEventBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.chooseEventBox.setFont(font)
        self.chooseEventBox.setObjectName("chooseEventBox")
        self.verticalLayout.addWidget(self.chooseEventBox)
        self.addIt = QtWidgets.QPushButton(addNoteWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.addIt.setFont(font)
        self.addIt.setObjectName("addIt")
        self.verticalLayout.addWidget(self.addIt)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(addNoteWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(addNoteWidget)
        QtCore.QMetaObject.connectSlotsByName(addNoteWidget)

    def retranslateUi(self, addNoteWidget):
        _translate = QtCore.QCoreApplication.translate
        addNoteWidget.setWindowTitle(_translate("addNoteWidget", "Добавить заметку"))
        self.label.setText(_translate("addNoteWidget", "Выбрать событие:"))
        self.addIt.setText(_translate("addNoteWidget", "Добавить"))
