# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 344)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "О приложении"))
        self.plainTextEdit.setPlainText(_translate("Form", "\"Помощник - приложение для хранения, просмотра и создания событий и заметок, привязанных к определённой дате.\n"
"\n"
"Для просмотра событий необходимо нажать кнопку \"Мои заметки\", выбрать дату на календаре слева или назавние события в списке справа. Событие отобразиться в специальном виджете.  Нажав кнопку \"Сохранить как файл\" вы сможете сохранить события, показанные в окне, файлом\n"
"\n"
"Для добавления события необходимо нажать кнопку \"Добавить событие\". В открывшемся окне выберите дату, время и введите событие. Нажмите кнопку \"Добавить\". Событие сохранено.\n"
"\n"
"Для добавления заметки к событию необходимо нажать кнопку \"Добавить заметку\". В открывшемя окне выберите событие, к которому хотите привязать заметку, введите текст заметки, нажмите кнопку \"Добавить\". Заметка сохранена.\n"
"\n"
"При нажатии на кнопку \"Получить таблицу с событиями\", в папке с приложением создаётся таблица, в которой содержаться все ваши событияю "))
