# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handhelper_add_event_window4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addeventWindow(object):
    def setupUi(self, addeventWindow):
        addeventWindow.setObjectName("addeventWindow")
        addeventWindow.resize(793, 608)
        self.horizontalLayout = QtWidgets.QHBoxLayout(addeventWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.calendarWidget = QtWidgets.QCalendarWidget(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.calendarWidget.setFont(font)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_2.addWidget(self.calendarWidget)
        self.label_2 = QtWidgets.QLabel(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.timeEdit = QtWidgets.QTimeEdit(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_2.addWidget(self.timeEdit)
        self.withoutTimeBox = QtWidgets.QCheckBox(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.withoutTimeBox.setFont(font)
        self.withoutTimeBox.setObjectName("withoutTimeBox")
        self.verticalLayout_2.addWidget(self.withoutTimeBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.addIt = QtWidgets.QPushButton(addeventWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.addIt.setFont(font)
        self.addIt.setObjectName("addIt")
        self.verticalLayout.addWidget(self.addIt)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(addeventWindow)
        QtCore.QMetaObject.connectSlotsByName(addeventWindow)

    def retranslateUi(self, addeventWindow):
        _translate = QtCore.QCoreApplication.translate
        addeventWindow.setWindowTitle(_translate("addeventWindow", "Добавить событие"))
        self.label.setText(_translate("addeventWindow", "Выберите дату:"))
        self.label_2.setText(_translate("addeventWindow", "Выберите время:"))
        self.withoutTimeBox.setText(_translate("addeventWindow", "Весь день"))
        self.addIt.setText(_translate("addeventWindow", "Добавить"))
